---
- name: 'Ensure Google Chrome is provisioned for package manager dnf'
  include_tasks: 'tasks-dnf.yml'
  when: ansible_pkg_mgr in ('dnf5', 'dnf')

- name: 'Ensure Google Chrome is provisioned for package manager apt'
  include_tasks: 'tasks-apt.yml'
  when: ansible_pkg_mgr in ('apt')

- fail:
    msg: ERROR This role is not setup to deal with package manager {{ ansible_pkg_mgr }}
  when: ansible_pkg_mgr not in ('apt', 'dnf', 'dnf5')
